site: pandafy
url: #yoururl
title: pandafy
description: dev logs
twitter:
  username: pandafy
  card: summary
  creator: pandafy
author:
  twitter: _pandafy_
  name: Gagan Deep
  avatar: https://avatars1.githubusercontent.com/u/32094433?s=460&u=e294318a11a54ea7dabd1179e7438146c5528bf1&v=4
  email: pandafy.dev@gmail.com
  url: pandafy.me
permalink: pretty

baseurl: pandafy.me

highlighter: none

exclude:
  - .jekyll-cache

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
